
version: '2'
volumes:
  db-data:
  log-data:
  consul-config:
  consul-data:

networks:
  edgex-network:
    driver: "bridge"

services:
  mongodb:
    build: 
      context: ./mongo
      dockerfile: Dockerfile
    image: edgexfoundry/mongo
    container_name: edgex-mongo
    ports:
      - "27017:27017"
    networks:
      edgex-network:
        aliases:
            - edgex-core-volume
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume

  config-seed:
    build: 
      context: ./core-config-seed-go
      dockerfile: Dockerfile
    image: edgexfoundry/docker-core-config-seed-go
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed
    networks:
      edgex-network:
        aliases:
            - edgex-core-config-seed
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume
      - consul
      
  volume:
    build:
      context: ./edgex-volume
      dockerfile: Dockerfile
    image: edgexfoundry/docker-edgex-volume
    container_name: edgex-files
    networks:
      edgex-network:
        aliases:
            - edgex-core-volume
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
      
  consul:
    image: arm32v6/consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes:
      - db-data:/data/db
      - log-data:/edgex/logs
      - consul-config:/consul/config
      - consul-data:/consul/data
    depends_on:
      - volume 


