ConfigPath = './config'
GlobalPrefix = 'config'
ConsulProtocol = 'http'
ConsulHost = 'edgex-core-consul'
ConsulPort = 8500
IsReset = true
FailLimit = 30
FailWaitTime = 3
AcceptablePropertyExtensions = ['.toml','.yaml', '.yml', '.properties']
YamlExtensions = ['.yaml','.yml']
TomlExtensions = ['.toml']